replicaCount: 2

image:
  repository: 306372151512.dkr.ecr.ap-southeast-2.amazonaws.com/calculator-app
  pullPolicy: IfNotPresent
  tag: "27"

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

ingress:
  enabled: true
  className: alb
  host: calculator.local